no se

diff --git a/.local/bin/tm-tree b/.local/bin/tm-tree
--- a/.local/bin/tm-tree
+++ b/.local/bin/tm-tree
@@ -6,33 +6,33 @@
 #   https://github.com/petobens/dotfiles/blob/master/tmux/tmux_tree
 
 single_mode() {
-	session_name="${1}"
-	if test "${DISPLAY_TMUXP}" -eq 1; then
-		if $(tmux has-session -t "${session_name}" >&/dev/null); then
-			:
-		else
-			tmuxp_conf="${HOME}/.tmuxp/${session_name}.yaml"
-			if test -e "${tmuxp_conf}"; then
-				cat "${tmuxp_conf}"
-				return
-			fi
-		fi
-	fi
-	display_session "${session_name}"
+    session_name="${1}"
+    if test "${DISPLAY_TMUXP}" -eq 1; then
+        if $(tmux has-session -t "${session_name}" >&/dev/null); then
+            :
+        else
+            tmuxp_conf="${HOME}/.tmuxp/${session_name}.yaml"
+            if test -e "${tmuxp_conf}"; then
+                cat "${tmuxp_conf}"
+                return
+            fi
+        fi
+    fi
+    display_session "${session_name}"
 }
 
 # Display a single sesssion
 display_session() {
-	session_name="${1}"
-	session_id=$(tmux ls -F '#{session_id}' \
-		-f "#{==:#{session_name},${session_name}}")
-	if test -z "${session_id}"; then
-		echo "Unknown session: ${session_name}"
-		return 1
-	fi
-	# Display contents of session's active pane. Kudos: tmux-fzf
-	# https://github.com/sainnhe/tmux-fzf/blob/master/scripts/.preview
-	tmux capture-pane -ep -t ${session_id}
+    session_name="${1}"
+    session_id=$(tmux ls -F '#{session_id}' \
+        -f "#{==:#{session_name},${session_name}}")
+    if test -z "${session_id}"; then
+        echo "Unknown session: ${session_name}"
+        return 1
+    fi
+    # Display contents of session's active pane. Kudos: tmux-fzf
+    # https://github.com/sainnhe/tmux-fzf/blob/master/scripts/.preview
+    tmux capture-pane -ep -t ${session_id} -J
 }
 
 # Display a full tree, with selected session highlighted.
@@ -40,26 +40,26 @@ display_session() {
 # in the output.
 # This is the original tmux_tree script (see kudos).
 tree_mode() {
-	highlight="${1}"
-	tmux ls -F'#{session_id}' | while read -r s; do
-		S=$(tmux ls -F'#{session_id}#{session_name}: #{T:tree_mode_format}' | grep ^"$s")
-		session_info=${S##$s}
-		session_name=$(echo "$session_info" | cut -d ':' -f 1)
-		if [[ -n "$highlight" ]] && [[ "$highlight" == "$session_name" ]]; then
-			echo -e "\033[1;34m$session_info\033[0m"
-		else
-			echo -e "\033[1m$session_info\033[0m"
-		fi
-		# Display each window
-		tmux lsw -t"$s" -F'#{window_id}' | while read -r w; do
-			W=$(tmux lsw -t"$s" -F'#{window_id}#{T:tree_mode_format}' | grep ^"$w")
-			echo "  ﬌ ${W##$w}"
-		done
-	done
+    highlight="${1}"
+    tmux ls -F'#{session_id}' | while read -r s; do
+        S=$(tmux ls -F'#{session_id}#{session_name}: #{T:tree_mode_format}' | grep ^"$s")
+        session_info=${S##$s}
+        session_name=$(echo "$session_info" | cut -d ':' -f 1)
+        if [[ -n "$highlight" ]] && [[ "$highlight" == "$session_name" ]]; then
+            echo -e "\033[1;34m$session_info\033[0m"
+        else
+            echo -e "\033[1m$session_info\033[0m"
+        fi
+        # Display each window
+        tmux lsw -t"$s" -F'#{window_id}' | while read -r w; do
+            W=$(tmux lsw -t"$s" -F'#{window_id}#{T:tree_mode_format}' | grep ^"$w")
+            echo "  ﬌ ${W##$w}"
+        done
+    done
 }
 
 usage() {
-	cat <<-END
+    cat <<-END
 		Usage: $0 [<options>] [<session_name>]
 
 		Options:
@@ -69,7 +69,7 @@ usage() {
 
 		A session name of "*Last*" is replaced with the client's last session.
 	END
-	# Note 'END' above most be fully left justified.
+    # Note 'END' above most be fully left justified.
 }
 
 # What are we displaying?
@@ -82,26 +82,26 @@ mode="single"
 DISPLAY_TMUXP=0
 
 while getopts ":hpt" opt; do
-	case $opt in
-	h)
-		usage
-		exit 0
-		;;
-	p) DISPLAY_TMUXP=1 ;;
-	t) mode="tree" ;;
-	\?) echo "Invalid option: -$OPTARG" >&2 ;;
-	esac
+    case $opt in
+    h)
+        usage
+        exit 0
+        ;;
+    p) DISPLAY_TMUXP=1 ;;
+    t) mode="tree" ;;
+    \?) echo "Invalid option: -$OPTARG" >&2 ;;
+    esac
 done
 
 shift $(($OPTIND - 1))
 SESSION="$1"
 
 if test "${SESSION}" == '*Last*'; then
-	SESSION=$(tmux display-message -p "#{client_last_session}")
-	if test -z "${SESSION}"; then
-		echo "No last session."
-		exit 0
-	fi
+    SESSION=$(tmux display-message -p "#{client_last_session}")
+    if test -z "${SESSION}"; then
+        echo "No last session."
+        exit 0
+    fi
 fi
 
 case "${mode}" in
